version: '3'

services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./:/code
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  php:
    image: yiisoftware/yii2-php:7.2-fpm
    ports:
      - 9000:9000
    volumes:
      - ./server/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/code
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  serverMysql:
    image: mysql:5.7.22
    container_name: mysql
    depends_on:
      - php
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./server/mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - serverMysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
